export interface ClientDto {
  readonly clientId: string | null;
  readonly NUM_CLIENTE: number | null;
  readonly RAZON: string | null;
  readonly DOMICILIO: string | null;
  readonly TELEFONO: string | null;
  readonly FAX: string | null;
  readonly CP: string | null;
  readonly LOCALIDAD: string | null;
  readonly IVA: string | null;
  readonly CONTACTO: string | null;
  readonly CUIT: string | null;
  readonly CALIF: string | null;
  readonly SALDO: number | null;
  readonly PROVINCIA: string | null;
  readonly MAIL: string | null;
  readonly CODI_VENDE: string | null;
  readonly CODI_TRANSPOR: number | null;
  readonly CUENTA: string | null;
  readonly ESTADO: string | null;
  readonly IMPOR_LIMI_CREDI: number | null;
  readonly CANTI_DIAS_VENCI: number | null;
  readonly LUGAR_ENTREGA: string | null;
  readonly CONTACTO_PAGO: string | null;
  readonly LUGAR_PAGO: string | null;
  readonly TELE_PAGO: string | null;
  readonly OBSER_PAGO: string | null;
  readonly LISTA_CODI: string | null;
  readonly PORCEN_DESCUEN: number | null;
  readonly FECHA_ALTA: string | null;
  readonly DOC_PATH: string | null;
  readonly AGRU_1: string | null;
  readonly AGRU_2: string | null;
  readonly AGRU_3: string | null;
  readonly CODI_ORI: string | null;
  readonly CTA_CTE_POR_TOTAL: string | null;
  readonly CONDI_VENTA: string | null;
  readonly NOM_FANTASIA: string | null;
  readonly INGRE_BRUTOS: string | null;
  readonly PORCEN_RECARGO: number | null;
  readonly CODI_ANTE: string | null;
  readonly OBSER_2: string | null;
  readonly PORCEN_COMI: number | null;
  readonly WEB: string | null;
  readonly CODI_COBRA: string | null;
  readonly POTENCIAL: string | null;
  readonly PORCEN_COMI_COBRO: number | null;
  readonly EXEN_PERCEP_IB: string | null;
  readonly EXEN_PERCEP_IVA: string | null;
  readonly EXEN_PERCEP_GCIA: string | null;
  readonly OBSER_ESTADO: string | null;
  readonly COD_COMP: string | null;
  readonly PERCEP_IB_PORCEN: number | null;
  readonly PORCEN_GANAN: number | null;
  readonly EXCLU_COMI_ARTI: string | null;
  readonly CODI_TARJE: string | null;
  readonly TARJETA_NUME: string | null;
  readonly CELULAR: string | null;
  readonly DIA_CUMPLE: string | null;
  readonly MES_CUMPLE: string | null;
  readonly OBSER_DATOS_LABO: string | null;
  readonly OBSER_GARANTES: string | null;
  readonly OBSER_DOCUMENTACION: string | null;
  readonly CODI_PAIS: string | null;
  readonly GLN: string | null;
  readonly LIMI_CODI: string | null;
  readonly MAIL_AUTO: string | null;
  readonly DIA_VISITA: string | null;
  readonly FECHA_MODI: string | null;
  readonly USER_MODI: string | null;
  readonly USER_ALTA: string | null;
  readonly MONE_PEDI_DEFAULT: string | null;
  readonly FECHA_INTE: string | null;
  readonly CODI_TABLA_GALENOS: string | null;
  readonly LIMI_CREDI_DIAS: number | null;
  readonly FECHA_VENCI_TARJE: string | null;
  readonly TIPO_DOC: string | null;
  readonly NUM_DOC: string | null;
  readonly COD_SUB_CATE_IVA: string | null;
  readonly PASS_WEB: string | null;
  readonly RUTEO_EJE_X: number | null;
  readonly RUTEO_EJE_Y: number | null;
  readonly USUARIO_WEB: string | null;
  readonly ORDEN_DE_VISITA: number | null;
  readonly CONDI_VENTA_MAX: string | null;
  readonly NRO_CUENTA_PROVEEDOR: string | null;
  readonly CODIGO_ACTIVIA: string | null;
  readonly CODI_ZONA: string | null;
  readonly CODI_VENDE_RESPON: string | null;
  readonly PORCEN_MARGEN_MIN: number | null;
  readonly DIAS_FRECUENCIA_CONTACTO: number | null;
  readonly ANIO_NAC: number | null;
  readonly FECHA_VENCI_PASSWORD: string | null;
}

export interface VoucherDto {
  readonly NUM: number;
  readonly TIPO: string;
  readonly FECHA: string;
  readonly CLIENTE: number;
  readonly SUB_TOTAL: number;
  readonly TOTAL: number;
  readonly ESTADO: string;
  readonly VENCIMIENTO: string;
  readonly SALDO: number;
  readonly FAC_VAL: string;
  readonly OBSER: string;
  readonly PORCEN_IVA: number;
  readonly CATE_IVA: string;
  readonly REMI_NUME: number | null;
  readonly CANTI_DIAS_VENCI: number | null;
  readonly ACTUA_PRECIOS: string;
  readonly PRECIO_INCLU_IVA: string;
  readonly ACTUA_STOCK: string;
  readonly TOTAL_COSTO: number;
  readonly PRECE_TIPO: string | null;
  readonly PRECE_NUM: number | null;
  readonly MONE_COTI: number;
  readonly TIPO_MOVI: string;
  readonly NUM_FISCAL: number;
  readonly IMPOR_IVA: number;
  readonly PORCEN_IVA2: number;
  readonly IMPOR_IVA2: number;
  readonly PORCEN_DESCUEN: number;
  readonly CODI_VENDE: string;
  readonly CODI_BARRA: string | null;
  readonly MONE: string;
  readonly CODI_TRANSPOR: string | null;
  readonly SUB_TOTAL_EXEN: number;
  readonly RECI_NUME: number | null;
  readonly USER_ALTA: string;
  readonly ASIEN_NUME: number;
  readonly ASIEN_REVER: number | null;
  readonly LISTA_CODI: string;
  readonly FECHA_ALTA: string;
  readonly TURNO_CODI: number | null;
  readonly MONE_ALTER_COTI: number;
  readonly TOTAL_COSTO_C_IVA: number;
  readonly BULTOS: number;
  readonly PESO: number;
  readonly CODI_ACTI: string | null;
  readonly PORCEN_COMI: number;
  readonly FECHA_ANU: string | null;
  readonly PROVINCIA: string;
  readonly CODI_TRACK: string | null;
  readonly ESTA_ENVIO: string;
  readonly CANCELADO: string;
  readonly PROVISORIO: string | null;
  readonly CONDI_VENTA: string;
  readonly LUGAR_ENTRE: number;
  readonly PORCEN_IMPUES: number;
  readonly IMPOR_IMPUES: number;
  readonly ITEMS_CON_DTOS: string;
  readonly IMPOR_COMI_PEND: number;
  readonly FECHA_PAGO: string;
  readonly CODI_COBRA: string | null;
  readonly CODI_ORI: string | null;
  readonly USER_MODI: string | null;
  readonly FECHA_MODI: string | null;
  readonly NOMBRE_PACIENTE: string | null;
  readonly ASIEN_NUME_CMV: number | null;
  readonly ASIEN_ANU_CMV: number | null;
  readonly PORCEN_COMI_COBRO: number;
  readonly IMPOR_COMI_PEND_COBRO: number;
  readonly USER_ANU: string | null;
  readonly CODI_CENCO: string | null;
  readonly CODI_LEGAJO: string | null;
  readonly PUNTOS: string | null;
  readonly PERCEP_IB_PORCEN: number;
  readonly PERCEP_IB_IMPOR: number;
  readonly PERCEP_IVA_PORCEN: number;
  readonly PERCEP_IVA_IMPOR: number;
  readonly PERCEP_GCIA_PORCEN: number;
  readonly PERCEP_GCIA_IMPOR: number;
  readonly FECHA_ENVIO: string | null;
  readonly IMPOR_ENVIO: number | null;
  readonly REMI_CODI: number | null;
  readonly TIPO_SENIA: string;
  readonly USER_AUTO: string | null;
  readonly FECHA_AUTO: string | null;
  readonly PERCEP_IB_PROVIN: string | null;
  readonly PERCEP_IB2_PORCEN: number;
  readonly PERCEP_IB2_IMPOR: number;
  readonly PERCEP_IB2_PROVIN: string | null;
  readonly FECHA_PRESEN: string | null;
  readonly NUME_CAE: string;
  readonly FECHA_CAE: string;
  readonly ERROR_CAE: string;
  readonly FECHA_ALTA_CAE: string;
  readonly CODI_PACIEN: string | null;
  readonly IMPOR_COMI_PEND_ARTI: number;
  readonly PORCEN_COMI_ARTI: number;
  readonly FECHA_INTE: string | null;
  readonly CODI_PAGO_ELECTRONICO: string | null;
  readonly CANT_CUOTAS: number | null;
  readonly PORCEN_INTERES_DIARIO: number | null;
  readonly DIA_VENCI_CUOTA: number | null;
  readonly PORCEN_RECARGO_CUOTAS: number | null;
  readonly CODI_PAGO_ELEC_CONVER: string | null;
  readonly ID_CAE: number;
  readonly TIPO_COMI_ARTI: string | null;
  readonly HOST_NOMBRE: string;
  readonly CODI_CONTACTO: number;
  readonly DEVO_VALORES: string | null;
  readonly FECHA_REGIS: string | null;
  readonly CODI_PERCEP_IB: string | null;
  readonly CODI_PERCEP_IB2: string | null;
  readonly REMI_NUME2: string | null;
  readonly REMI_NUME3: string | null;
  readonly REMI_NUME4: string | null;
  readonly REMI_NUME5: string | null;
  readonly CODI_ENTIDAD: string | null;
  readonly FECHA_IMPRE: string;
  readonly FECHA_IMPRE_ADIC: string | null;
  readonly DIAS_PROME_PAGO: number | null;
  readonly DIAS_PROME_MORA: number | null;
  readonly ID_TABLA: string | null;
  readonly CODI_LEGAJO2: string | null;
  readonly CODI_MAQ: string | null;
  readonly CODI_LEGAJO3: string | null;
  readonly OBSER_CONTROL: string | null;
  readonly PAIS_ORIGEN: string | null;
  readonly NRO_BL: string | null;
  readonly CUIT_COMPRO: string;
  readonly CODI_PAIS: string | null;
  readonly PERCEP_IB_MAS: number;
  readonly VOLUMEN: string | null;
  readonly FECHA_ENTREGA: string | null;
  readonly CODI_TARJE: string | null;
  readonly TARJETA_NUME: string | null;
  readonly ANULA_FC_CREDITO: string | null;
  readonly IMPOR_IVA3: number | null;
  readonly PORCEN_IVA3: number | null;
  readonly IMPOR_IVA4: number | null;
  readonly PORCEN_IVA4: number | null;
}

export interface ClientDiscountDto {
  readonly clientNumber: number;
  readonly discounts: {
    readonly agrupacion: string;
    readonly porcentaje_descuento: number;
  }[];
}
